<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Signika|Thasadith" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <script type="text/javascript" src="js/utilities.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <title>Tuitui Blog</title>
  </head>
  <body>
    <main class="container bgopaque flex">
      <div class="col-two-third">
        <article id="billet">
          <div class="">
            <h2 class="title_article">Mildford Sound</h2>
            <img src="images/Voyages/mildford/mildford_map.png" alt="newZealand"/>
          </div>
          <div class="billet_content">
              <div class="info_billet">
                <h4>Date publication</h4>
                <h4><a href="#">Auteur</a></h4>
                <h4><a href="#">Catégorie</a></h4>
              </div>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
                dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                mollit anim id est laborum.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
                dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                mollit anim id est laborum.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
                dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                mollit anim id est laborum.</p>
          </div>
          <div class="readmore">
            <a href="#" id="previous_billet"><i class="fas fa-chevron-left"></i></a>
            <a href="#" id="next_billet"><i class="fas fa-chevron-right"></i></a>
          </div>
        </article>
      </div>
      <div  id="aside" class="col-one-third">
          <form class="connexion" action="index.html" method="post">
            <fieldset>
              <legend>Connexion</legend>
              <ul>
                <li>
                  <label for="pseudo">
                  <input type="text" id="pseudo" name="pseudo" placeholder="pseudo" value="">
                  </label>
                </li>
                <li>
                  <label for="pw">
                  <input type="password"  id="pw" placeholder="password" name="pw" value="">
                  </label>
                </li>
                <li>
                  <button type="button" name="button">Valider</button>
                </li>
              </ul>
            </fieldset>
          </form>
          <div class="search">
            <label for=""><h3>Rechercher</h3></label>
            <input type="text" name="name" value="">
          </div>
          <div class="categ">
            <h3>Catégorie</h3>
            <p></p>
          </div>
        </div>
    </main>
  </body>
</html>
