<div class="col-two-third ">
  <article id="billet">
    <div class="">
      <h2 class="title_article">Mildford Sound</h2>
      <img src="images/Voyages/mildford/mildford0.jpg" alt="newZealand" />
    </div>
    <div class="billet_content">
        <div class="info_billet">
          <h4>Date publication</h4>
          <h4><a href="#">Auteur</a></h4>
          <h4><a href="#">Catégorie</a></h4>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
          exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
          dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
          Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
          mollit anim id est laborum.</p>
    </div>
    <div class="readmore">
      <a href="billet.php"><i class="fas fa-ellipsis-h"></i></a>
    </div>
  </article>
</div>
