

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="index.html" method="post">
      <fieldset>
        <legend>Nouveau billet</legend>
        <label for="">
          <input type="text" name="" value="">
        </label>
        <input type="datetime" name="" value="">
        <textarea name="name" rows="8" cols="80"></textarea>
      </fieldset>
    </form>
  </body>
</html>
